# Generated by Django 3.1.2 on 2020-11-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201106_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='wayfarer_project/static/post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='wayfarer_project/static/default-user-image-2.png', null=True, upload_to='wayfarer_project/static/user_images'),
        ),
    ]
