# Generated by Django 3.1.2 on 2020-11-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201103_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
